[build]
  publish = "MarketYouthMusicians.github.io"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.62.2"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
